### PR TITLE
[CU-860rj8cp1]: add required weapons

### PR DESCRIPTION
**Pull request by FlavianEng**
## Changelog:
- Add two constant for default settings
- Classic weapon can't be removed from the selected weapons  

## Checklist before requesting a review
-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_CU-{ClickUp Id}_**] **_{summary}_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860rj8cp1 Make classic weapon required](https://app.clickup.com/t/860rj8cp1)

**Comment by MASBERNATQ** [comment]
Il faut que tu m'envoies les `defaultSettings` dans l'événement _game-information_ pour que les joueurs adverses puissent avoir les infos correspondantes.

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
