### PR TITLE
[CU-860qkvy0e] Send theme in player objects

### PR DESCRIPTION
**Pull request by FlavianEng**
>__Warning__
>After merge this PR, follow the procedure below:
>`docker compose down`
>`docker volume rm battleship-back_battleship-db`
>`docker compose up`
>`npm run fixture`

## Changelog: 
- Send theme in players objects for the following events :
  - `game-created`
  - `player-joined`
  - `game-informations`
- fix(engine): remove src from authorised boats
- Relocation of some files
- Specification of theme type in theme entity (_drop your docker volume and run fixtures_)

## Checklist before requesting a review
-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_ClickUp Id_**] **_summary_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860qkvy0e US: Theme logic](https://app.clickup.com/t/860qkvy0e)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
