### PR TITLE
Cu 376ax2f – Setup architecture

### PR DESCRIPTION
**Pull request by FlavianEng**
- Add TS path aliases
- Update Jest config 
- Create architecture folders 
- Format code

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-376ax2f Setup Archi](https://app.clickup.com/t/376ax2f)

**Review by MaximeWrlz — DISMISSED** [review]

**Review by ManonFargues — APPROVED** [review]

**Review by ManonFargues — APPROVED** [review]

**Review by ManonFargues — APPROVED** [review]

**Review by MaximeWrlz — APPROVED** [review]

**Pull request merged**
