### PR TITLE
[CU-3c6jpeb] Game settings : Generate board game

### PR DESCRIPTION
**Pull request by FlavianEng**
>__Warning__
> This PR contains **BREAKING CHANGES**

## Changelog: 
- Generate dynamically board game
- **[breaking changes]** : Type of board dimensions has changed. cf below 

New GameSettings :
```TypeScript
export type GameSettings = {
  boardDimensions: [xAxisMaxValue: number, yAxisMaxValue: number];
  hasShipsSafetyZone: boolean;
  timePerTurn: number;
  weapons: Weapon[];
};
``` 

## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_ClickUp Id_**] **_summary_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-3c6jpeb Game settings : generate board game](https://app.clickup.com/t/3c6jpeb)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
