### PR TITLE
[860re62t6-us-fix-connection]: fix connection issues

### PR DESCRIPTION
**Pull request by FlavianEng**
>__Warning__
> You need to add the new line of `.env.sample` file into `.env` file

## Changelog:  
- Client is no longer disconnected when leaving
- Reset game state when a player leaves
- (Out of scope) Tests for engine in CI

## Checklist before requesting a review
-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_ClickUp Id_**] **_summary_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860re62t6 US: Fix connection](https://app.clickup.com/t/860re62t6)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
