### PR TITLE
Create check-mergeability.yml

### PR DESCRIPTION
**Pull request by FlavianEng**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-376aw3g Setup CI](https://app.clickup.com/t/376aw3g)

**Review by MaximeWrlz — DISMISSED** [review]

**Review by DrakenLine — DISMISSED** [review]

**Review by DrakenLine — APPROVED** [review]

**Review by MaximeWrlz — APPROVED** [review]

**Pull request merged**
