### PR TITLE
Weapons api calls

### PR DESCRIPTION
**Pull request by FlavianEng**
>**Ready to review (draft state only avoid merging before PR#37)**
> Do NOT merge before PR #37  

- When creating a game the weapons are now obtained from database (Only for guest)

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860pbj6p7 Weapons Api calls](https://app.clickup.com/t/860pbj6p7)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
