### PR TITLE
Create base engine

### PR DESCRIPTION
**Pull request by FlavianEng**
* Create the status handling 
* Create the gameMode handling
* Add the handling of game configuration 
* In a nutshell, all the engine part that are not the progressing game

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-3c0t6wf Create base engine](https://app.clickup.com/t/3c0t6wf)

**Review by MASBERNATQ — DISMISSED** [review]

**Review by MASBERNATQ — APPROVED** [review]

**Review by DrakenLine — APPROVED** [review]

**Review by MaximeWrlz — APPROVED** [review]

**Pull request merged**
