### PR TITLE
Create two types of fixtures 

### PR DESCRIPTION
**Pull request by FlavianEng**
- Create 2 types of fixtures
- Create a nice cli for convenience

image

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860pbj6y1 Create two types of fixtures](https://app.clickup.com/t/860pbj6y1)

**Review by MaximeWrlz — DISMISSED** [review]

**Review by MASBERNATQ — APPROVED** [review]

**Review by MaximeWrlz — APPROVED** [review]

**Pull request merged**
