### PR TITLE
Add a prefix to all routes 

### PR DESCRIPTION
**Pull request by FlavianEng**
* Add the prefix /api
* The swagger is now available at baseRoute/docs

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-39w8raq Prefix with /api](https://app.clickup.com/t/39w8raq)

**Review by MaximeWrlz — APPROVED** [review]

**Review by MaximeWrlz — DISMISSED** [review]

**Review by MASBERNATQ — APPROVED** [review]

**Review by MaximeWrlz — APPROVED** [review]

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
