### PR TITLE
[CU-860rec81g] : Dockerize backend for development environment

### PR DESCRIPTION
**Pull request by FlavianEng**
> __Note__
> **The backend launch changes !** 
> Now, you'll have to run `bin/app-mac` or `bin/app-linux` depending your OS

>__Warning__
> The environment variable `POSTGRESQL_HOST` has been updated.
> The environment variable `POSTGRESQL_PORT` has been updated.

## Changelog:  
 - Create docker development environment
 - Update husky pre push
 - Create a script to easily manipulate development environment
 - Remove useless `password` column of user 

## Checklist before requesting a review
-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_CU-{ClickUp Id}_**] **_{summary}_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860rec81g Dockerize backend for development](https://app.clickup.com/t/860rec81g)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
