### PR TITLE
[CU-860qgxuz2]: Refactor game engine into entities

### PR DESCRIPTION
**Pull request by FlavianEng**
>__Warning__
> The docker port has been updated

## Changelog: 
- Rework handling of error
- Update docker port
- Split `Game instance service` into several specific services
- Merge validators files
- Rename all engine types. `type` and `interface` are now suffixed with `Type`. `enum` are now suffixed with `Enum`
- Add .md template for format Pull request. ClickUp Id : CU-860radewh
 
## Checklist before requesting a review

-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**ClickUp ID**]: **_summary_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860qgxuz2 Refactor game engine into entities](https://app.clickup.com/t/860qgxuz2)

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
