### PR TITLE
[CU-860re8gaz]: Send source of images in game entities

### PR DESCRIPTION
**Pull request by FlavianEng**
## Changelog:  
- refactor(engine): rename player manager to player service
- feat(engine): create type with skin
- feat(engine): give theme of players to boats objects
- feat(engine): add skin of weapon in object

## Checklist before requesting a review
-   [x] I have performed a self-review of my code
-   [x] My pull request title respect the naming convention: [**_ClickUp Id_**] **_summary_**

### CODE REVIEW

**Comment by FlavianEng** [comment]
Task linked: [CU-860re8gaz Send source of images in game entities](https://app.clickup.com/t/860re8gaz)

**Review by MASBERNATQ — APPROVED** [review]

**Review by MASBERNATQ — APPROVED** [review]

**Pull request merged**
